"""Declarative base and column conventions shared by every model.

The explicit naming convention matters for Alembic: without it, SQLAlchemy
generates unnamed constraints and autogenerated downgrade steps cannot drop
them by name.
"""

import uuid
from datetime import datetime
from typing import Annotated

from sqlalchemy import BigInteger, DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# Reusable column types. UUIDs are the only identifiers exposed publicly, so
# sequential integer keys are never leaked to clients.
UUIDPrimaryKey = Annotated[
    uuid.UUID,
    mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4),
]

#: Wall-clock creation time, defaulted by the database so rows inserted by a
#: migration or by psql are stamped consistently with rows inserted by the app.
CreatedAt = Annotated[
    datetime,
    mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    ),
]

#: A required timestamp defaulted by the database but not indexed, for columns
#: that are read alongside a row rather than filtered or sorted on.
DefaultedTimestamp = Annotated[
    datetime,
    mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now()),
]

UpdatedAt = Annotated[
    datetime,
    mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    ),
]

OptionalTimestamp = Annotated[
    datetime | None,
    mapped_column(DateTime(timezone=True), nullable=True),
]

#: File sizes are stored as bigint so a future limit increase needs no migration.
FileSize = Annotated[int, mapped_column(BigInteger, nullable=False)]
